/**
 * Interview completion component: a DVI summary card (from the app-computed
 * core) plus the printable report preview. Component scores are never shown.
 */

import { FileText, RefreshCw } from 'lucide-react';
import { useState } from 'react';
import { ErrorAlert } from './ErrorAlert';
import { InterviewCore } from '@/lib/questions';
import { DVI_BANDS } from '@/lib/dvi';

interface AssessmentCompleteProps {
  report: string;
  core: InterviewCore | null;
  onStartNew: () => void;
}

const ROUTE_LABELS: Record<string, string> = {
  'RR-Basic': 'Basic Research',
  'RR-AD': 'Research · Advanced Demand',
  'DD-Basic': 'Development',
  'DD-AD': 'Development · Advanced Demand',
};

function dviBadgeClasses(dvi: number): string {
  if (dvi >= DVI_BANDS.STRONG) return 'bg-green-100 text-green-800 border-green-300';
  if (dvi >= DVI_BANDS.MODERATE) return 'bg-amber-100 text-amber-800 border-amber-300';
  return 'bg-red-100 text-red-800 border-red-300';
}

export function AssessmentComplete({ report, core, onStartNew }: AssessmentCompleteProps) {
  const [previewError, setPreviewError] = useState('');

  const convertMarkdownToHTML = (markdown: string): string => {
    let html = markdown
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^#### (.*$)/gim, '<h4>$1</h4>')
      .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/gim, '<em>$1</em>')
      .replace(/_(.*?)_/gim, '<em>$1</em>')
      .replace(/\n\n/gim, '</p><p>');

    html = html
      .split('\n')
      .map((line) => {
        if (line.trim() === '') return '';
        if (line.match(/^<[h1-6]/)) return line;
        return line.startsWith('<') ? line : `<p>${line}</p>`;
      })
      .join('\n');

    return html
      .replace(/<p><\/p>/g, '')
      .replace(/<p>(<[h1-6])/g, '$1')
      .replace(/(<\/[h1-6][^>]*>)<\/p>/g, '$1');
  };

  const viewReport = (): void => {
    setPreviewError('');
    try {
      if (!report || report.trim().length === 0) {
        setPreviewError('The report content is invalid.');
        return;
      }
      const dviLine =
        core != null
          ? `<p><strong>Route:</strong> ${core.route} &nbsp;·&nbsp; <strong>DVI:</strong> ${core.dvi.toFixed(
              2
            )} / 5.00 — ${core.interpretation}</p>`
          : '';

      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AIaaS Demand Summary</title>
    <style>
        @media print { body { margin: 0; font-size: 12pt; } .no-print { display: none !important; } }
        body { font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1, h2, h3 { color: #1e40af; page-break-after: avoid; }
        h1 { border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        strong { color: #1e3a8a; }
        .header { text-align: center; margin-bottom: 24px; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.9em; color: #666; }
        .toolbar { background: #f8fafc; border-bottom: 1px solid #e2e8f0; padding: 12px 20px; margin: -20px -20px 20px -20px; display: flex; align-items: center; gap: 12px; }
        .print-btn { background: #7c3aed; color: white; padding: 8px 20px; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 500; }
        .print-hint { color: #64748b; font-size: 13px; }
    </style>
</head>
<body>
    <div class="no-print toolbar">
        <button class="print-btn" onclick="window.print()">Print</button>
        <span class="print-hint">Select "Save as PDF" as the printer destination to save as PDF</span>
    </div>
    <div class="header">
        <h1>AIaaS Demand Summary</h1>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    <div class="content">
        ${dviLine}
        ${convertMarkdownToHTML(report)}
    </div>
    <div class="footer">
        <p>Generated by the AIaaS Demand Viability Index chatbot. The DVI is a preliminary, study-specific operational index.</p>
    </div>
</body>
</html>`;

      const previewWindow = window.open('', '_blank');
      if (!previewWindow) {
        setPreviewError('Popup blocked. Please allow popups for this site and try again.');
        return;
      }
      previewWindow.document.write(htmlContent);
      previewWindow.document.close();
      previewWindow.focus();
    } catch {
      setPreviewError('Failed to open report preview. Please try again.');
    }
  };

  return (
    <div className="space-y-4" role="region" aria-label="Interview complete">
      {previewError && (
        <ErrorAlert message={previewError} severity="warning" onClose={() => setPreviewError('')} />
      )}

      {core && (
        <div className="p-5 bg-white border border-gray-200 rounded-xl shadow-sm">
          <div className="flex items-center justify-between gap-3 flex-wrap">
            <div>
              <p className="text-xs uppercase tracking-wide text-gray-500">
                {core.route} · {ROUTE_LABELS[core.route] ?? core.route}
              </p>
              <p className="text-sm text-gray-600">{core.interpretation}</p>
            </div>
            <div
              className={`px-4 py-2 rounded-lg border text-center ${dviBadgeClasses(core.dvi)}`}
              aria-label={`Demand Viability Index ${core.dvi.toFixed(2)} out of 5`}
            >
              <div className="text-2xl font-bold leading-none">{core.dvi.toFixed(2)}</div>
              <div className="text-[10px] uppercase tracking-wide mt-1">DVI / 5.00</div>
            </div>
          </div>
          <p className="text-xs text-gray-400 mt-3">
            The DVI is a preliminary, study-specific demand signal — not a formal validated scale or proof of market demand.
          </p>
        </div>
      )}

      <div className="p-6 bg-green-50 border-2 border-green-300 rounded-xl text-center">
        <h2 className="text-xl font-bold text-green-800 mb-2">Interview Complete!</h2>
        <p className="text-gray-700 mb-4">
          Thank you for taking part in the AIaaS demand study. Preview your summary to save or print it below.
        </p>

        <div className="flex justify-center gap-3 flex-wrap mb-4">
          <button
            onClick={viewReport}
            className="bg-blue-600 text-white px-6 py-3 rounded-xl hover:bg-blue-700 transition flex items-center gap-2 font-medium shadow-sm"
            aria-label="View summary in a new tab with option to print as PDF"
          >
            <FileText size={20} aria-hidden="true" />
            View Summary
          </button>
        </div>

        <button
          onClick={onStartNew}
          className="bg-gray-600 text-white px-6 py-3 rounded-xl hover:bg-gray-700 transition flex items-center gap-2 font-medium shadow-sm mx-auto"
          aria-label="Start a new interview"
        >
          <RefreshCw size={20} aria-hidden="true" />
          Start New Interview
        </button>
      </div>
    </div>
  );
}
